In [25]:
import numpy as np
import matplotlib.pyplot as plt
from pygsp import graphs, filters, plotting
import pygsp as pg
from numpy.random import default_rng
from numpy.random import randint
from random import sample
import random
import cvxpy as cp

plotting.BACKEND = 'matplotlib'
plt.rcParams['figure.figsize'] = (10, 5)

In [26]:
def createGraph(Nodes,i,graphType):
    while True:
        s = np.array(sample(range(1, 10000), 1))
        G = pg.graphs.Sensor(N=Nodes, seed = s)
        typeName = 'Sensor'
            
        if (G.is_connected() and not(G.is_directed())):
            break
    if i==0:        
        print(typeName)
           
    G.compute_fourier_basis()
    W = np.random.uniform(size=(2,1))
    x =  G.U[:,1:3]@W
    x = x/np.max(np.abs(x))
    eigenvalue = G.e
    print(eigenvalue[1:4])

    return G,x

In [27]:
def computeMainSignal(signals,k,N):
    x = np.zeros((N,1))
    for i in range(k):
        x = x + signals[:,i].reshape(N,1)
    return x

In [28]:
def computeSmoothness(signals,graphs,k):
    smoothness = []
    sumOverSmoothness = 0
    for i in range(k):
        smoothness.append(signals[:,i].T@graphs[i].L@signals[:,i])
        sumOverSmoothness = sumOverSmoothness + smoothness[i]
    return sumOverSmoothness,smoothness

In [29]:
def decomposeGraphSignal(mainSignal,signals,graphs,k,N):
    A = np.tile(np.identity(N), (1, k))
    
    H = np.zeros((N*k,N*k))
    for i in range(k):
        g = graphs[i].L
        H[i*N:(i+1)*N,i*N:(i+1)*N] = g.toarray()
        
        
    X = cp.Variable((N*k,1))
    objective = cp.Minimize(cp.quad_form(X, H)) 
    
    constraints = [ A @ X == mainSignal]
    prob = cp.Problem(objective, constraints)
    prob.solve(verbose=True)
    
    temp = X.value
    X_hat = temp.reshape(N,k, order='F')
    
    return X_hat

In [30]:
def makeMeanZero(signals,k):
    for i in range(k):
            signals[:,i] = signals[:,i] - np.mean(signals[:,i])
            
    return signals

In [31]:
def calculateSNR(est_signals,signals,k):
    SNR = np.zeros((1,k))
    for i in range(k):
        SNR[0,i]=(10*np.log10(np.linalg.norm(signals[:,i])**2/np.linalg.norm(signals[:,i]-est_signals[:,i])**2))
    return SNR

In [32]:
N = 100  # number of nodes
k = 5    # number of graphs
np.random.seed(0)
random.seed(0)
iteration = 200
av_snr = np.zeros((1,k))

for itera in range(1,iteration+1):
    print('############################################# iteration = ',itera,' ########################################')
    # create graph and graph signals
    graphType = randint(1, 3, 1)
    graph_list = []
    signals = np.zeros((N,k))
    for i in range(k):
        G , x = createGraph(N,i,graphType)
        graph_list.append(G)
        signals[:,[i]] = x

    # calculate the main signal : x = x1+x2+...+x4
    mainSignal = computeMainSignal(signals,k,N)
    mainSignal = mainSignal - np.mean(mainSignal)

    # decompose graph signal
    estimated_signals = decomposeGraphSignal(mainSignal,signals,graph_list,k,N)

    # calculate graph signals' smoothness
    sumOverSmoothness,smoothness = computeSmoothness(signals,graph_list,k)
    print('smoothness:')
    print(smoothness)
    print('sum over smoothness:',sumOverSmoothness)

    # calculate estimated graph signals' smoothness
    sumOverSmoothness_est,smoothness_est = computeSmoothness(estimated_signals,graph_list,k)
    print('smoothness_est:')
    print(smoothness_est)
    print('sum over smoothness_est:',sumOverSmoothness_est)

    # make mean of the estimated signals zero to remove DC values
    estimated_signals = makeMeanZero(estimated_signals,k)

    # calculate SNRs
    SNRs = calculateSNR(estimated_signals,signals,k)
    print('SNR:',SNRs)
    av_snr = av_snr + SNRs/iteration

    # compute objective values
    objectiveValue = sumOverSmoothness
    objectiveValue_est = sumOverSmoothness_est
    print('objectiveValue:',objectiveValue)
    print('objectiveValue_est:',objectiveValue_est)

    # compute error
    error = np.linalg.norm(mainSignal-estimated_signals@np.ones((k,1)))
    print('error:',error)
    
    
print('av_snr: ',av_snr)
print('total_av_snr: ',np.mean(av_snr))

############################################# iteration =  1  ########################################
Sensor
[0.37258419 0.4387519  0.66748598]
[0.05875928 0.28807215 0.32534728]
[0.11825027 0.18386095 0.34892946]
[0.13188762 0.24836801 0.32811761]
[0.22832208 0.31831286 0.57057818]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3568
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: of

[0.21710875 0.2775315  0.38441583]
[0.21125473 0.23768327 0.39527917]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3704
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.27e+00   3.03e+03   1.00e-01   8.07e-03s
  50   1.9720e+01   3.84e-09   4.08e-

[0.17767475 0.42033836 0.49380116]
[0.3216424  0.36576084 0.54743327]
[0.19534231 0.27252408 0.36441923]
[0.18032488 0.24005892 0.47943504]
[0.28325166 0.38601409 0.48471403]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3720
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        

[0.16916663 0.24865815 0.44653883]
[0.2407239  0.25219457 0.59216968]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3509
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.29e+00   3.03e+03   1.00e-01   7.38e-03s
  50   1.9890e+01   3.77e-09   4.08e-

Sensor
[0.10936596 0.15820464 0.19905809]
[0.14476067 0.18289815 0.23216035]
[0.15510059 0.26714613 0.49704745]


2021-12-03 14:56:55,505:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.31636648 0.33906441 0.66401556]
[0.13051726 0.28452428 0.34328659]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3617
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.36e+00   1.54e+03   1.00e-01   6.81e-03s
  50   1.2189e+01   3.93e-09   2.07e-

Sensor
[0.20441248 0.27149521 0.50653492]
[0.10416252 0.24958263 0.36562186]
[0.09417247 0.19349963 0.3420285 ]
[0.12718723 0.27693666 0.38774265]
[0.23322007 0.3195405  0.40218203]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3555
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.17006999 0.27695754 0.44948152]
[0.20248965 0.40507961 0.53190411]
[0.2679804  0.37994953 0.53099253]
[0.20267191 0.34502236 0.45524924]
[0.1070237  0.31024994 0.40286071]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3590
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        

2021-12-03 14:57:00,863:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.22514128 0.27949768 0.41531508]
[0.14004157 0.35107595 0.42948463]
[0.17449009 0.36621282 0.50133408]
[0.20994905 0.32495799 0.43275587]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3663
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.51e+00  

Sensor
[0.21317785 0.37779076 0.58982529]
[0.07658364 0.15574391 0.38063417]
[0.17820252 0.29189458 0.47526107]
[0.14529224 0.33247013 0.55036153]
[0.19156718 0.32269862 0.43653641]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3656
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

2021-12-03 14:57:03,909:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.15931332 0.26614064 0.32347218]
[0.20640906 0.28183673 0.55644805]
[0.24096223 0.34215123 0.54193737]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3513
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   1.96e+00   2.04e+03   1.00e-01   6.63e-03s
  

2021-12-03 14:57:05,404:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.09909185 0.18444386 0.46441808]
[0.26343921 0.29176019 0.57215318]
[0.18839203 0.31352987 0.50653156]
[0.21333219 0.31476022 0.49926682]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3784
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.21e+00  

Sensor
[0.19942259 0.29213025 0.55922825]
[0.05977112 0.2180196  0.40890541]
[0.15579925 0.27299151 0.34081771]
[0.13782648 0.25364948 0.43702077]
[0.15321138 0.18007677 0.27562457]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3631
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.18496927 0.21060548 0.45454512]
[0.14980603 0.20126252 0.25735671]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3498
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.40e+00   2.62e+03   1.00e-01   7.09e-03s
  50   1.6005e+01   1.41e-08   3.53e-

2021-12-03 14:57:10,738:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.09427874 0.24371039 0.39660255]
[0.22848617 0.31727824 0.56115606]
[0.2133973  0.25783152 0.42342357]
[0.29914291 0.32956674 0.4692053 ]
[0.2511747  0.29949681 0.4639516 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3547
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.16970513 0.203127   0.50788493]
[0.2245672  0.25039313 0.34549512]
[0.26654969 0.33044491 0.47946151]
[0.17994552 0.21151133 0.35758428]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3573
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.11e+00  

[0.06286015 0.17569012 0.43635701]
[0.27452887 0.30468281 0.4986786 ]
[0.33284448 0.45071201 0.55552538]
[0.05462273 0.23975071 0.29315307]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3612
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.46e+00  

[0.23171714 0.35788559 0.51809436]
[0.16310215 0.24980857 0.3993469 ]
[0.19665926 0.25391143 0.36953742]
[0.14213545 0.21246685 0.42059444]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3435
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.77e+00  

plsh   1.2839e+01   4.73e-16   1.02e-14   --------   2.81e-02s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    12.8387
run time:             2.81e-02s
optimal rho estimate: 2.93e-02

smoothness:
[1.9129653511919638, 2.8998039079856457, 3.162570146823268, 4.704691060119535, 2.6608619843042236]
sum over smoothness: 15.340892450424636
smoothness_est:
[1.4969631301055117, 2.521840498160325, 2.4309917875297873, 3.8034343389586525, 2.5855078243532796]
sum over smoothness_est: 12.838737579107555
SNR: [[10.30660011 15.4517024  12.81142736 16.00468276 17.91861665]]
objectiveValue: 15.340892450424636
objectiveValue_est: 12.838737579107555
error: 1.6698387267888598e-15
############################################# iteration =  73  ########################################
Sensor
[0.15843885 0.17559997 0.3947009 ]
[0.10648766 0.1799753  0.35616304]
[0.18001486 0.23417626 0.37879036]
[0.27687711 0.30757534 0.48880618]
[0.08619355 0.171734

2021-12-03 14:57:19,691:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.16596503 0.21003762 0.48554762]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3577
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.47e+00   2.11e+03   1.00e-01   6.30e-03s
  50   9.6804e+00   1.46e-08   2.84e-08   1.60e-02   1.86e-02s
plsh   9.

[0.10551786 0.25374312 0.42152193]
[0.19263893 0.2958991  0.50174891]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3673
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.64e+00   2.33e+03   1.00e-01   7.53e-03s
  50   1.1834e+01   1.47e-08   3.14e-

Sensor
[0.28508925 0.3022389  0.37000274]
[0.26073899 0.28426484 0.56544382]
[0.19714416 0.23488123 0.5134635 ]
[0.09162779 0.12367022 0.28522283]
[0.24276601 0.37396763 0.49653315]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3589
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.13591176 0.17407742 0.27962111]
[0.15504504 0.2356469  0.48848439]
[0.13828154 0.25651635 0.35235795]
[0.24127924 0.27088485 0.50302471]
[0.30362817 0.38581262 0.51037102]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3554
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        

[0.24826523 0.33842156 0.49459714]
[0.10939994 0.19768522 0.31218383]
[0.13431143 0.26031027 0.46035078]
[0.2107282  0.34806212 0.55536292]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3526
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.47e+00  

[0.17662566 0.20203838 0.28749523]
[0.19287022 0.22908034 0.56265659]
[0.21463539 0.22873011 0.31345821]
[0.21343626 0.25772966 0.36341076]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3589
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.25e+00  

[0.18692321 0.2521482  0.48255044]
[0.20158978 0.27061919 0.34445209]
[0.26443849 0.28404413 0.4816387 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3570
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.30e+00   1.83e+03   1.00e-01   7.80e-03s
  

Sensor
[0.15451587 0.27598845 0.32573835]
[0.27717944 0.31274718 0.55661705]
[0.27969098 0.31685424 0.62235607]
[0.14151151 0.20986368 0.32926988]
[0.24127924 0.27088485 0.50302471]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3481
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.0796438  0.14273262 0.30684479]
[0.22176942 0.44210991 0.58872464]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3667
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.64e+00   3.13e+03   1.00e-01   7.05e-03s
  50   1.9341e+01   1.53e-08   4.21e-

2021-12-03 14:57:36,523:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.15230687 0.30625516 0.38384876]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3560
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.58e+00   3.00e+03   1.00e-01   6.41e-03s
  50   1.5087e+01   1.30e-08   4.04e-08   1.89e-02   1.91e-02s
plsh   1.

[0.23897888 0.25853741 0.41269551]
[0.14038991 0.35663717 0.69155457]
[0.16100102 0.46430447 0.57644803]
[0.29196938 0.31108833 0.5505634 ]
[0.34242325 0.40908286 0.68798405]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3682
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        

2021-12-03 14:57:39,885:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.16821087 0.26065921 0.44817562]
[0.21621779 0.24695782 0.3162163 ]
[0.22660553 0.31360064 0.55001722]
[0.04501179 0.20321753 0.35642593]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3571
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.13e+00  

2021-12-03 14:57:41,583:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.17250322 0.29268539 0.48561926]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3535
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.79e+00   2.35e+03   1.00e-01   6.33e-03s
  50   1.9472e+01   4.71e-09   3.16e-08   1.00e-01   1.43e-02s
plsh   1.

  50   2.1549e+01   4.19e-09   3.07e-08   1.00e-01   1.64e-02s
plsh   2.1549e+01   7.73e-16   8.23e-15   --------   2.42e-02s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    21.5494
run time:             2.42e-02s
optimal rho estimate: 3.02e-02

smoothness:
[2.269867140270505, 6.643894781580883, 5.185936154577401, 5.600707843516851, 6.663562315972053]
sum over smoothness: 26.363968235917696
smoothness_est:
[2.1531788769746654, 4.749367496627534, 4.660801135232462, 4.9873732689479695, 4.998712558797045]
sum over smoothness_est: 21.549433336579675
SNR: [[11.00742324 12.38047448 16.48382667 16.71003357 13.17271355]]
objectiveValue: 26.363968235917696
objectiveValue_est: 21.549433336579675
error: 2.505906984569267e-15
############################################# iteration =  132  ########################################
Sensor
[0.12795092 0.24474308 0.50793167]
[0.2474678  0.30629185 0.3849509 ]
[0.18061617 0.22090175 0.4327646

[0.22881626 0.32171663 0.42290802]
[0.17886424 0.29372569 0.38025581]
[0.05488097 0.18511254 0.25472963]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3485
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.16e+00   2.26e+03   1.00e-01   6.50e-03s
  

Sensor
[0.21744182 0.2507308  0.3780176 ]
[0.21110917 0.25402326 0.44318456]
[0.2719204  0.29626505 0.49949953]
[0.22218529 0.2644774  0.37614037]
[0.14595697 0.22369138 0.53004318]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3503
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

[0.19626773 0.27441424 0.58912995]
[0.16921332 0.25812326 0.52310246]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3728
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.36e+00   2.18e+03   1.00e-01   7.65e-03s
  50   1.0178e+01   3.98e-09   2.93e-

2021-12-03 14:57:49,435:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.11271777 0.28848561 0.38721153]
[0.12679244 0.23812261 0.34616365]
[0.21058384 0.39095003 0.55199084]
[0.19932068 0.34163219 0.45053189]
[0.14804631 0.23637764 0.44960234]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3605
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

Sensor
[0.24555497 0.31403204 0.54813301]
[0.11486003 0.16571028 0.39903344]
[0.19000859 0.27718163 0.43625946]
[0.23570697 0.28817526 0.33500084]
[0.17396213 0.18161207 0.30709996]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3580
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

2021-12-03 14:57:52,526:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.11647271 0.26935505 0.41185786]
[0.23285368 0.2552491  0.34299674]
[0.25857291 0.41765925 0.47656813]
[0.22837832 0.29515392 0.33495606]
[0.15086626 0.23352837 0.34093586]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3681
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 

2021-12-03 14:57:54,588:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.13459202 0.24345848 0.42147064]
[0.23824677 0.34863119 0.52478571]
[0.23573537 0.28090901 0.47196793]
[0.23418864 0.32384452 0.52791599]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3550
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.03e+00  

2021-12-03 14:57:57,150:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.25993919 0.2915152  0.52864106]
[0.19577084 0.23838349 0.37826971]
[0.25459695 0.29104122 0.35576831]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3522
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.21e+00   2.82e+03   1.00e-01   8.27e-03s
  

[0.14243301 0.21658799 0.46432318]
[0.2132305  0.27639425 0.54410395]
[0.25149675 0.37822918 0.56481522]
[0.18515978 0.22522755 0.27985373]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3570
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.63e+00  

[0.17701856 0.25436327 0.56243972]
[0.12987047 0.22241293 0.35231564]
[0.11913012 0.16894564 0.36487437]
[0.17420693 0.31211777 0.45008143]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3474
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.90e+00  

  50   1.2101e+01   2.89e-09   3.04e-08   1.00e-01   1.54e-02s
plsh   1.2101e+01   2.87e-16   4.59e-15   --------   2.27e-02s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    12.1013
run time:             2.27e-02s
optimal rho estimate: 3.82e-02

smoothness:
[4.3798931377817585, 1.5920404280656744, 3.4425158743959243, 2.4679840815466294, 3.302211894966057]
sum over smoothness: 15.184645416756045
smoothness_est:
[3.038131019422434, 1.597981385133577, 2.7267317191453824, 1.9555376333716668, 2.7829633867894934]
sum over smoothness_est: 12.101345143862552
SNR: [[11.8200342  12.29108418 13.61479185 12.23073271 13.65295175]]
objectiveValue: 15.184645416756045
objectiveValue_est: 12.101345143862552
error: 1.3858549535759098e-15
############################################# iteration =  175  ########################################
Sensor
[0.10324236 0.28484174 0.41078842]
[0.16484476 0.25265428 0.41273409]
[0.27533427 0.30431383 0.4

[0.19215001 0.2440491  0.28064852]
[0.16608525 0.26725269 0.48910529]
[0.15850912 0.25895231 0.46643572]
[0.19536016 0.2898572  0.34478109]
[0.25463855 0.30128836 0.52590336]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3561
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        

2021-12-03 14:58:04,201:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.16554908 0.24453181 0.33408959]
[0.17116059 0.243139   0.48659247]
[0.16393275 0.32794946 0.42412562]
[0.23983683 0.32176245 0.5513118 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3612
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.23e+00  

[0.08553567 0.14327878 0.33679923]
[0.20965723 0.28144736 0.4496008 ]
[0.21323532 0.29123134 0.46634378]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3560
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.31e+00   2.93e+03   1.00e-01   7.25e-03s
  

[0.12302519 0.37680814 0.56371355]
[0.20817992 0.28380218 0.40601241]
[0.22531104 0.26503081 0.48276238]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3604
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.28e+00   1.54e+03   1.00e-01   6.86e-03s
  

          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.81e+00   2.83e+03   1.00e-01   7.27e-03s
  50   2.1916e+01   1.36e-08   3.82e-08   1.98e-02   2.12e-02s
plsh   2.1916e+01   3.52e-16   7.61e-15   --------   2.88e-02s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    21.9161
run time:             2.88e-02s
optimal rho estimate: 9.28e-03

smoothness:
[8.409457630996432, 6.511550317040351, 3.951850183311654, 0.8050951891269271, 5.842389172298491]
sum over smoothness: 25.520342492773857
smoothness_est:
[7.337984726441538, 4.771370347834459, 3.5595334627245356, 1.1807357257005433, 5.066521961662222]
sum over smoothness_est: 21.916146224363295
SNR: [[18.37082418 13.26646061 15.41900697 12.03729344 17.24966284]]
objectiveValue: 25.520342492773857
objectiveValue_est: 21.916146224363295
error: 2.2688034453

Sensor
[0.09326582 0.28840486 0.35656534]
[0.27769451 0.29963135 0.42981393]
[0.15199894 0.32492818 0.49439345]
[0.12168604 0.17221502 0.44932357]
[0.26639717 0.32762775 0.50085437]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 500, constraints m = 100
          nnz(P) + nnz(A) = 3482
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho 