In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pygsp import graphs, filters, plotting
import pygsp as pg
from numpy.random import default_rng
from numpy.random import randint
from random import sample
import random
import cvxpy as cp

plotting.BACKEND = 'matplotlib'
plt.rcParams['figure.figsize'] = (10, 5)

In [2]:
def createGraph(Nodes,i,graphType):
    while True:
        s = np.array(sample(range(1, 10000), 1))
        G = pg.graphs.Sensor(N=Nodes, seed = s)
        typeName = 'Sensor'
            
        if (G.is_connected() and not(G.is_directed())):
            break
    if i==0:        
        print(typeName)
           
    G.compute_fourier_basis()
    W = np.random.uniform(size=(2,1))
    x =  G.U[:,1:3]@W
    x = x/np.max(np.abs(x))
    eigenvalue = G.e
    print(eigenvalue[1:4])

    return G,x

In [3]:
def computeMainSignal(signals,k,N):
    x = np.zeros((N,1))
    for i in range(k):
        x = x + signals[:,i].reshape(N,1)
    return x

In [4]:
def computeSmoothness(signals,graphs,k):
    smoothness = []
    sumOverSmoothness = 0
    for i in range(k):
        smoothness.append(signals[:,i].T@graphs[i].L@signals[:,i])
        sumOverSmoothness = sumOverSmoothness + smoothness[i]
    return sumOverSmoothness,smoothness

In [5]:
def decomposeGraphSignal(mainSignal,signals,graphs,k,N):
    A = np.tile(np.identity(N), (1, k))
    
    H = np.zeros((N*k,N*k))
    for i in range(k):
        g = graphs[i].L
        H[i*N:(i+1)*N,i*N:(i+1)*N] = g.toarray()
        
        
    X = cp.Variable((N*k,1))
    objective = cp.Minimize(cp.quad_form(X, H)) 
    
    constraints = [ A @ X == mainSignal]
    prob = cp.Problem(objective, constraints)
    prob.solve(verbose=True)
    
    temp = X.value
    X_hat = temp.reshape(N,k, order='F')
    
    return X_hat

In [6]:
def makeMeanZero(signals,k):
    for i in range(k):
            signals[:,i] = signals[:,i] - np.mean(signals[:,i])
            
    return signals

In [7]:
def calculateSNR(est_signals,signals,k):
    SNR = np.zeros((1,k))
    for i in range(k):
        SNR[0,i]=(10*np.log10(np.linalg.norm(signals[:,i])**2/np.linalg.norm(signals[:,i]-est_signals[:,i])**2))
    return SNR

In [8]:
N = 450  # number of nodes
k = 5    # number of graphs
np.random.seed(0)
random.seed(0)
iteration = 200
av_snr = np.zeros((1,k))

for itera in range(1,iteration+1):
    print('############################################# iteration = ',itera,' ########################################')
    # create graph and graph signals
    graphType = randint(1, 3, 1)
    graph_list = []
    signals = np.zeros((N,k))
    for i in range(k):
        G , x = createGraph(N,i,graphType)
        graph_list.append(G)
        signals[:,[i]] = x

    # calculate the main signal : x = x1+x2+...+x4
    mainSignal = computeMainSignal(signals,k,N)
    mainSignal = mainSignal - np.mean(mainSignal)

    # decompose graph signal
    estimated_signals = decomposeGraphSignal(mainSignal,signals,graph_list,k,N)

    # calculate graph signals' smoothness
    sumOverSmoothness,smoothness = computeSmoothness(signals,graph_list,k)
    print('smoothness:')
    print(smoothness)
    print('sum over smoothness:',sumOverSmoothness)

    # calculate estimated graph signals' smoothness
    sumOverSmoothness_est,smoothness_est = computeSmoothness(estimated_signals,graph_list,k)
    print('smoothness_est:')
    print(smoothness_est)
    print('sum over smoothness_est:',sumOverSmoothness_est)

    # make mean of the estimated signals zero to remove DC values
    estimated_signals = makeMeanZero(estimated_signals,k)

    # calculate SNRs
    SNRs = calculateSNR(estimated_signals,signals,k)
    print('SNR:',SNRs)
    av_snr = av_snr + SNRs/iteration

    # compute objective values
    objectiveValue = sumOverSmoothness
    objectiveValue_est = sumOverSmoothness_est
    print('objectiveValue:',objectiveValue)
    print('objectiveValue_est:',objectiveValue_est)

    # compute error
    error = np.linalg.norm(mainSignal-estimated_signals@np.ones((k,1)))
    print('error:',error)
    
    
print('av_snr: ',av_snr)
print('total_av_snr: ',np.mean(av_snr))

############################################# iteration =  1  ########################################
Sensor
[0.03158285 0.07100325 0.10882611]
[0.04200162 0.0523515  0.08870145]
[0.05083379 0.0551267  0.08920562]
[0.0559381  0.05989505 0.10349108]
[0.0506435  0.07293445 0.11618803]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17434
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: 

  50   2.6953e+01   4.86e-09   5.71e-08   1.00e-01   9.29e-01s
plsh   2.6953e+01   5.50e-16   1.08e-14   --------   1.70e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    26.9531
run time:             1.70e+00s
optimal rho estimate: 1.31e-02

smoothness:
[1.9299545204492077, 8.658219750770286, 8.852005478513409, 3.803079198844797, 4.7419171887423195]
sum over smoothness: 27.985176137320018
smoothness_est:
[2.021675142966587, 8.248145624166012, 8.380839306441004, 3.783943845558885, 4.518522936842981]
sum over smoothness_est: 26.95312685597547
SNR: [[24.48456357 28.26291669 27.4651169  27.96160172 25.51099792]]
objectiveValue: 27.985176137320018
objectiveValue_est: 26.95312685597547
error: 5.3159593350246076e-15
############################################# iteration =  6  ########################################


2021-12-03 14:50:56,313:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.0498458  0.07280417 0.11640954]
[0.04891071 0.05268543 0.08409226]
[0.05853166 0.06303884 0.11725142]
[0.06006478 0.0652168  0.1129662 ]
[0.04113579 0.05346677 0.07612131]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17546
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

  50   2.6700e+01   5.81e-09   5.47e-08   1.00e-01   1.14e+00s
plsh   2.6700e+01   5.94e-16   1.09e-14   --------   1.84e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    26.6998
run time:             1.84e+00s
optimal rho estimate: 1.19e-02

smoothness:
[7.397573980449996, 6.448172390201196, 2.7296584753592645, 3.5395496125270376, 7.393493394933297]
sum over smoothness: 27.50844785347079
smoothness_est:
[7.1267227637336585, 6.1538449895867995, 2.693702824710842, 3.5762595180521557, 7.1492393439996755]
sum over smoothness_est: 26.69976944008313
SNR: [[29.74652536 28.23012079 26.08740062 29.84510097 29.76126914]]
objectiveValue: 27.50844785347079
objectiveValue_est: 26.69976944008313
error: 5.297891211432144e-15
############################################# iteration =  11  ########################################
Sensor
[0.06160342 0.07630633 0.13073751]
[0.06283748 0.07133387 0.11696337]
[0.06075485 0.06650353 0.10789399

Sensor
[0.03525349 0.05731347 0.08321976]
[0.03417096 0.05904824 0.10293241]
[0.0601292  0.07149818 0.11360684]
[0.05242171 0.06780434 0.11575282]
[0.06083515 0.06678032 0.12979297]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17395
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

2021-12-03 14:51:48,788:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.04916576 0.06798242 0.11281403]
[0.04688566 0.06141703 0.08061428]
[0.05621548 0.06469099 0.1117819 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17446
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.32e+00   4.48e+03   1.00e-01   6.54e-01s


plsh   2.9989e+01   6.62e-16   1.12e-14   --------   1.29e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    29.9887
run time:             1.29e+00s
optimal rho estimate: 1.06e-02

smoothness:
[6.326524796763659, 4.9804405488273735, 7.0806827996235215, 6.654862710212149, 6.010858159889377]
sum over smoothness: 31.05336901531608
smoothness_est:
[6.138083703830234, 4.81646350629248, 6.731482429056418, 6.462009604041024, 5.840658785105713]
sum over smoothness_est: 29.98869802832587
SNR: [[27.97701361 26.99449252 26.9099433  28.57770508 27.77445489]]
objectiveValue: 31.05336901531608
objectiveValue_est: 29.98869802832587
error: 5.752570272488406e-15
############################################# iteration =  21  ########################################
Sensor
[0.05978105 0.06867751 0.12942783]
[0.05252484 0.06403373 0.12024441]
[0.05894883 0.07125455 0.12727355]
[0.05974679 0.06314603 0.10708091]
[0.0464709  0.06757788 0.108296

[0.04527528 0.05626253 0.10038512]
[0.04410177 0.07083627 0.09326207]
[0.05398796 0.06723767 0.11445922]
[0.04804046 0.05424257 0.07815954]
[0.0623716  0.06603947 0.11212448]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17536
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho      

smoothness:
[6.440403212837868, 6.221581918993084, 5.212022842696339, 5.483502382555882, 6.426917148597884]
sum over smoothness: 29.784427505681055
smoothness_est:
[6.2594566162208345, 5.939684210300444, 5.020112410922563, 5.225391435423635, 6.293233923153561]
sum over smoothness_est: 28.73787859602104
SNR: [[28.29975409 26.78282581 27.02229236 26.0608266  28.77950659]]
objectiveValue: 29.784427505681055
objectiveValue_est: 28.73787859602104
error: 5.117142728671733e-15
############################################# iteration =  30  ########################################
Sensor
[0.03689271 0.05335759 0.06334882]
[0.04930524 0.06417289 0.11483005]
[0.05262947 0.06554113 0.10879916]
[0.05367149 0.06488106 0.11343281]
[0.05072971 0.06301696 0.12253512]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
------

[0.03133531 0.05495767 0.06820792]
[0.05521363 0.06978184 0.12178305]
[0.04983249 0.07024977 0.12113151]
[0.06278184 0.06471717 0.12532967]
[0.04639507 0.05698766 0.13103714]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17541
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho      

2021-12-03 14:53:01,132:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05029448 0.07300798 0.10858703]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17701
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.25e+00   4.27e+03   1.00e-01   6.14e-01s
  50   2.2890e+01   5.73e-09   5.75e-08   1.00e-01   8.23e-01s
plsh   

  50   2.9197e+01   5.61e-09   6.45e-08   1.00e-01   8.54e-01s
plsh   2.9197e+01   7.72e-16   1.00e-14   --------   1.49e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    29.1971
run time:             1.49e+00s
optimal rho estimate: 1.23e-02

smoothness:
[4.643364481676182, 7.866312054345523, 8.977631712559024, 3.2654867259542923, 5.583237620770799]
sum over smoothness: 30.33603259530582
smoothness_est:
[4.4631872353055355, 7.453953806631976, 8.605580845022903, 3.254904039115833, 5.419459981164934]
sum over smoothness_est: 29.19708590724118
SNR: [[25.25132988 26.60878524 28.75334804 25.94357927 27.32962122]]
objectiveValue: 30.33603259530582
objectiveValue_est: 29.19708590724118
error: 5.238276702701902e-15
############################################# iteration =  40  ########################################
Sensor
[0.04364334 0.06582899 0.10905664]
[0.05462864 0.06138675 0.1313683 ]
[0.04160362 0.06628931 0.11642444]
[0

[0.05329134 0.05976358 0.09847904]
[0.05448164 0.06162557 0.1107957 ]
[0.0685144  0.07765518 0.13103861]
[0.04814861 0.05680266 0.09753738]
[0.05490416 0.05534641 0.13077931]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17283
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho      

2021-12-03 14:53:43,375:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05258996 0.06639401 0.11942806]
[0.04517038 0.04910844 0.0937367 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17426
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.31e+00   4.69e+03   1.00e-01   5.76e-01s
  50   2.9539e+01   5.83e-09   6.31

plsh   2.8105e+01   6.37e-16   1.44e-14   --------   1.38e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    28.1047
run time:             1.38e+00s
optimal rho estimate: 1.37e-02

smoothness:
[6.051763764121489, 9.635810078823358, 7.190561992296641, 5.243898026760693, 1.1584618227622534]
sum over smoothness: 29.280495684764432
smoothness_est:
[5.843169610486056, 8.99803901287338, 6.76013337504193, 5.157308862167771, 1.3460953649789678]
sum over smoothness_est: 28.104746225548105
SNR: [[26.88505478 26.53040924 25.87921902 27.60832775 23.16829701]]
objectiveValue: 29.280495684764432
objectiveValue_est: 28.104746225548105
error: 4.883619108694412e-15
############################################# iteration =  50  ########################################
Sensor
[0.03929963 0.04776565 0.08868404]
[0.04315625 0.0543099  0.08627119]
[0.0566571  0.07197371 0.11406034]
[0.04443994 0.04871801 0.08480043]
[0.05595973 0.07659957 0.140

[0.05026219 0.07032466 0.13616803]
[0.05543427 0.07155882 0.11571237]
[0.05550624 0.07288947 0.11832555]
[0.05457373 0.07685526 0.13030515]
[0.05220095 0.06197856 0.11389231]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17651
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho      

2021-12-03 14:54:24,162:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05949171 0.0659532  0.10609646]
[0.04688615 0.05267233 0.10105759]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17660
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.15e+00   4.74e+03   1.00e-01   5.86e-01s
  50   2.9002e+01   5.54e-09   6.38

smoothness:
[8.450896015287846, 5.840421644909302, 4.762051917033848, 7.195684656973181, 5.359506935124126]
sum over smoothness: 31.608561169328304
smoothness_est:
[8.117482578110748, 5.705276176511786, 4.647114373103115, 6.718609391904132, 5.197396412703258]
sum over smoothness_est: 30.385878932333036
SNR: [[27.69068503 27.52123185 25.3131831  25.71307434 26.51172349]]
objectiveValue: 31.608561169328304
objectiveValue_est: 30.385878932333036
error: 5.6954341460965936e-15
############################################# iteration =  60  ########################################
Sensor
[0.05487902 0.06654766 0.11495807]
[0.04905663 0.05572012 0.11638615]
[0.05368559 0.05748626 0.13309275]
[0.05245446 0.060423   0.1132037 ]
[0.05828573 0.0634472  0.09963217]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
----

[0.05896568 0.06433293 0.11532121]
[0.05491663 0.07636159 0.1178851 ]
[0.0561593  0.07341456 0.12684663]
[0.05317696 0.06593635 0.12057439]
[0.04281221 0.0607136  0.08751611]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17618
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho      

2021-12-03 14:55:13,893:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.0620274  0.07213041 0.12470008]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17754
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.21e+00   3.87e+03   1.00e-01   4.91e-01s
  50   2.6386e+01   5.67e-09   5.21e-08   1.00e-01   6.40e-01s
plsh   

plsh   2.5278e+01   6.86e-16   1.01e-14   --------   1.09e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    25.2785
run time:             1.09e+00s
optimal rho estimate: 1.33e-02

smoothness:
[3.6146558277292664, 7.838515456108228, 6.787183816148204, 2.3961734813773075, 5.616240665431739]
sum over smoothness: 26.252769246794745
smoothness_est:
[3.594898548561144, 7.464031169615026, 6.350724207799332, 2.4800386263770977, 5.3887793139414715]
sum over smoothness_est: 25.27847186629407
SNR: [[27.30044438 28.52250924 25.83553754 26.50342786 27.14019744]]
objectiveValue: 26.252769246794745
objectiveValue_est: 25.27847186629407
error: 5.04637700741431e-15
############################################# iteration =  73  ########################################
Sensor
[0.05213805 0.05689994 0.10509364]
[0.04267732 0.05672064 0.08882216]
[0.05638104 0.06470395 0.11516648]
[0.03880794 0.06668382 0.11485427]
[0.05336617 0.05974233 0.10

2021-12-03 14:55:38,740:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.03274363 0.06398616 0.09304705]
[0.04712458 0.06355728 0.1196266 ]
[0.04703121 0.0674807  0.09908572]
[0.03908933 0.06213395 0.10408252]
[0.05626934 0.07394341 0.13062497]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17637
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

smoothness:
[2.141508312222557, 1.9205775218667869, 2.939614882615958, 5.974678827383219, 4.483287065324042]
sum over smoothness: 17.45966660941256
smoothness_est:
[2.1498161756850283, 1.9430064055742584, 2.8617551012825406, 5.652429656918093, 4.26295008637404]
sum over smoothness_est: 16.86995742583396
SNR: [[29.04220699 28.04092645 26.86591038 28.42710891 27.50250405]]
objectiveValue: 17.45966660941256
objectiveValue_est: 16.86995742583396
error: 4.199054913939558e-15
############################################# iteration =  81  ########################################
Sensor
[0.04964092 0.06918537 0.11352824]
[0.0489302  0.05644955 0.08748423]
[0.05795392 0.07120773 0.12706821]
[0.05291416 0.06437003 0.11110139]


2021-12-03 14:55:58,487:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.0421556  0.05054753 0.07831505]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17550
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.89e+00   3.68e+03   1.00e-01   4.45e-01s
  50   2.2558e+01   5.08e-09   4.96e-08   1.00e-01   6.01e-01s
plsh   

plsh   2.9636e+01   6.22e-16   1.13e-14   --------   1.30e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    29.6360
run time:             1.30e+00s
optimal rho estimate: 1.22e-02

smoothness:
[6.446936637721818, 4.624345435252058, 8.632165687831597, 5.240138554283167, 5.830202729924273]
sum over smoothness: 30.773789045012915
smoothness_est:
[6.25472876077331, 4.579009455483002, 8.258515324890274, 5.005599125671858, 5.538152984622102]
sum over smoothness_est: 29.63600565144054
SNR: [[28.0598075  27.21333109 28.34979167 25.36384584 25.82275901]]
objectiveValue: 30.773789045012915
objectiveValue_est: 29.63600565144054
error: 5.51259693613478e-15
############################################# iteration =  86  ########################################
Sensor
[0.04093712 0.05734239 0.12630505]
[0.06092346 0.07034066 0.12748558]
[0.05556903 0.0748198  0.11099085]
[0.04504482 0.061216   0.10760449]
[0.05002739 0.05861392 0.1137693

2021-12-03 14:56:25,266:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.05417638 0.0682354  0.10432855]
[0.05747933 0.07125273 0.12452756]
[0.04788645 0.0758157  0.10724192]
[0.05122625 0.05597933 0.09870755]
[0.04853213 0.05362231 0.0781688 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17424
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

smoothness:
[2.1423627250635002, 4.035210065719745, 6.188173832122591, 4.745561547289041, 9.871089881145577]
sum over smoothness: 26.982398051340454
smoothness_est:
[2.2085284015534294, 3.901292869357414, 5.974784721279532, 4.605211701750222, 9.206548043718776]
sum over smoothness_est: 25.896365737659373
SNR: [[24.79907502 25.10499279 27.14620663 26.4784418  26.7989378 ]]
objectiveValue: 26.982398051340454
objectiveValue_est: 25.896365737659373
error: 4.824437571316573e-15
############################################# iteration =  94  ########################################
Sensor
[0.04413933 0.06550861 0.07502944]
[0.05164659 0.06382036 0.11173642]
[0.03774037 0.07315603 0.10993127]
[0.05980142 0.06546012 0.10659305]
[0.05803706 0.06757914 0.09978478]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
---

[0.04261293 0.06165017 0.10008058]
[0.03160282 0.05842241 0.07284984]
[0.04909654 0.05280189 0.11890078]
[0.059181   0.06920416 0.11142344]


2021-12-03 14:56:57,129:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05156979 0.06564909 0.10435765]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17436
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.13e+00   3.62e+03   1.00e-01   6.12e-01s
  50   2.1497e+01   5.52e-09   4.87e-08   1.00e-01   8.02e-01s
plsh   

  50   2.1811e+01   4.99e-09   6.16e-08   1.00e-01   8.35e-01s
plsh   2.1811e+01   5.31e-16   1.06e-14   --------   1.44e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    21.8110
run time:             1.44e+00s
optimal rho estimate: 1.16e-02

smoothness:
[7.01176902384375, 1.0429568559864641, 6.0026165056446485, 0.22353338425750507, 8.169160111896478]
sum over smoothness: 22.45003588162885
smoothness_est:
[6.756351966641079, 1.0863206567056303, 5.803477320914998, 0.34812002561112587, 7.81675461474976]
sum over smoothness_est: 21.811024584622594
SNR: [[30.45124414 22.98044801 30.40262221 19.30042631 30.35445267]]
objectiveValue: 22.45003588162885
objectiveValue_est: 21.811024584622594
error: 5.347463342316111e-15
############################################# iteration =  103  ########################################
Sensor
[0.05317714 0.06901339 0.11053116]
[0.04472483 0.06759431 0.09517821]
[0.06538284 0.07112375 0.114478

Sensor
[0.05978798 0.06310228 0.10316109]
[0.04419288 0.05103578 0.095586  ]
[0.05814766 0.06481791 0.08915376]
[0.05672159 0.0780243  0.1172883 ]
[0.04240947 0.04534735 0.10017219]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17369
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

2021-12-03 14:57:41,995:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05776591 0.05912279 0.11678818]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17425
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.00e+00   4.21e+03   1.00e-01   5.76e-01s
  50   2.4762e+01   5.27e-09   5.68e-08   1.00e-01   7.57e-01s
plsh   

plsh   2.6089e+01   4.89e-16   1.04e-14   --------   1.47e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    26.0894
run time:             1.47e+00s
optimal rho estimate: 1.21e-02

smoothness:
[6.482389438422422, 5.05494884105293, 6.546035400111033, 4.59355774626216, 4.363361894589625]
sum over smoothness: 27.040293320438174
smoothness_est:
[6.172377699414387, 4.881674542672429, 6.319408613644467, 4.472726556417005, 4.243221228821176]
sum over smoothness_est: 26.089408640969463
SNR: [[27.63066384 27.23480168 28.56454291 27.8286853  26.26844066]]
objectiveValue: 27.040293320438174
objectiveValue_est: 26.089408640969463
error: 5.235214517990608e-15
############################################# iteration =  114  ########################################
Sensor
[0.04979254 0.0632823  0.09872317]
[0.05263768 0.05630112 0.08536136]
[0.05918467 0.06694089 0.12919926]


2021-12-03 14:58:04,940:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05949834 0.06748093 0.09882223]
[0.04209397 0.05013541 0.07951275]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17679
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.21e+00   3.63e+03   1.00e-01   7.11e-01s
  50   2.4663e+01   5.62e-09   4.89

2021-12-03 14:58:14,320:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05896394 0.07155188 0.1137345 ]
[0.05226944 0.07324973 0.11932213]
[0.06525496 0.07244592 0.12779863]
[0.04456795 0.05980563 0.08442912]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17682
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.06e+00

plsh   3.2609e+01   5.62e-16   1.11e-14   --------   1.18e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    32.6094
run time:             1.18e+00s
optimal rho estimate: 1.50e-02

smoothness:
[7.593402034580463, 5.858817255177346, 3.846194100444068, 9.791233729231788, 7.1457836191533435]
sum over smoothness: 34.23543073858701
smoothness_est:
[7.195837804181161, 5.651000365440541, 3.7565088165525915, 9.207239729303122, 6.798767281396042]
sum over smoothness_est: 32.60935399687346
SNR: [[25.48555957 25.02831148 23.48636245 25.68824296 24.845937  ]]
objectiveValue: 34.23543073858701
objectiveValue_est: 32.60935399687346
error: 4.88903991327288e-15
############################################# iteration =  120  ########################################
Sensor
[0.04298451 0.05566663 0.10026648]
[0.04572425 0.07269714 0.10958706]
[0.0554201  0.0681237  0.10937175]
[0.04122374 0.05113477 0.10564879]
[0.05631349 0.06211572 0.10250

[0.04324229 0.05957189 0.09833092]
[0.05411137 0.06202261 0.10244952]
[0.05056687 0.05193615 0.11552029]


2021-12-03 14:58:44,689:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05262868 0.06582468 0.11128323]
[0.04970377 0.06623182 0.1315996 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17441
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.45e+00   3.04e+03   1.00e-01   4.42e-01s
  50   1.6213e+01   4.31e-09   4.10

smoothness:
[6.281606324719203, 9.63882157991388, 4.662943370278095, 11.703946514556336, 8.223278383252877]
sum over smoothness: 40.51059617272039
smoothness_est:
[6.150734319459023, 9.23369558230282, 4.619320263606033, 11.159708449270486, 7.9041009684673735]
sum over smoothness_est: 39.067559583105734
SNR: [[26.72452063 27.3822156  26.10586697 28.2655878  27.29228919]]
objectiveValue: 40.51059617272039
objectiveValue_est: 39.067559583105734
error: 6.0924686273308974e-15
############################################# iteration =  129  ########################################
Sensor
[0.04681211 0.06493294 0.10497833]
[0.06225308 0.06564297 0.11299828]
[0.05364809 0.07857368 0.10893462]
[0.0497855  0.05400498 0.10346081]
[0.05889696 0.06472276 0.10229431]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
----

2021-12-03 14:59:06,388:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.02066109 0.05541494 0.08035533]
[0.04275715 0.05366172 0.10719804]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17344
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.99e+00   3.76e+03   1.00e-01   4.79e-01s
  50   2.3237e+01   5.28e-09   5.07

2021-12-03 14:59:21,505:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.05280006 0.05659132 0.11115462]
[0.05503127 0.06537048 0.11564748]
[0.04200941 0.04816788 0.08037333]
[0.04481922 0.06661072 0.10821531]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17687
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.07e+00

  50   2.9566e+01   6.27e-09   4.80e-08   1.00e-01   8.56e-01s
plsh   2.9566e+01   1.14e-15   1.30e-14   --------   1.50e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    29.5663
run time:             1.50e+00s
optimal rho estimate: 1.28e-02

smoothness:
[5.4347021870727925, 6.974162765007101, 5.12252682085868, 4.791479724547459, 8.29651525377339]
sum over smoothness: 30.619386751259423
smoothness_est:
[5.276682530871048, 6.700865966338091, 5.055877817600779, 4.642331260586792, 7.890509508713878]
sum over smoothness_est: 29.566267084110585
SNR: [[27.77902443 27.60980809 29.32377884 26.09956535 28.20118855]]
objectiveValue: 30.619386751259423
objectiveValue_est: 29.566267084110585
error: 5.142388144324507e-15
############################################# iteration =  139  ########################################
Sensor
[0.04927132 0.06720353 0.1190708 ]
[0.04596588 0.05611382 0.09168746]
[0.05140929 0.05919394 0.10990963]


[0.04325795 0.05976336 0.09563158]
[0.07139393 0.07894783 0.10825141]


2021-12-03 15:00:04,298:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.04560366 0.06300074 0.10422163]
[0.02948381 0.05631171 0.0946371 ]
[0.05584326 0.06019873 0.12540172]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17643
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.39e+00   3.48e+03   1.00e-01   7.80e-01s


  50   2.1669e+01   4.90e-09   4.09e-08   1.00e-01   1.12e+00s
plsh   2.1669e+01   5.65e-16   1.03e-14   --------   1.93e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    21.6687
run time:             1.93e+00s
optimal rho estimate: 1.33e-02

smoothness:
[3.4803045684382434, 2.981234129754447, 4.112674227667721, 6.094233561988944, 5.862129183148124]
sum over smoothness: 22.53057567099748
smoothness_est:
[3.301373407540027, 2.9033865328353685, 4.075537477638153, 5.820307441988034, 5.568045724698486]
sum over smoothness_est: 21.668650584700067
SNR: [[24.05543434 25.79148845 29.02023375 27.84229898 26.9924773 ]]
objectiveValue: 22.53057567099748
objectiveValue_est: 21.668650584700067
error: 4.828599698772844e-15
############################################# iteration =  148  ########################################
Sensor
[0.05215884 0.06068198 0.08397782]
[0.05817888 0.07465989 0.11015273]
[0.06239202 0.06587299 0.10453256]

Sensor
[0.05882535 0.07327138 0.10987863]
[0.05950569 0.07941398 0.12908267]
[0.05977182 0.06327182 0.10860586]
[0.04044893 0.04969958 0.08503562]
[0.0351952  0.05632725 0.10211689]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17496
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

2021-12-03 15:01:02,607:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.04142139 0.06924057 0.1091536 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17632
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.32e+00   5.51e+03   1.00e-01   9.51e-01s
  50   3.0613e+01   5.83e-09   7.42e-08   1.00e-01   1.26e+00s
plsh   

  50   2.1981e+01   4.54e-09   4.00e-08   1.00e-01   1.34e+00s
plsh   2.1981e+01   6.31e-16   1.10e-14   --------   2.26e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    21.9814
run time:             2.26e+00s
optimal rho estimate: 1.43e-02

smoothness:
[4.165999031616858, 4.983698129357887, 4.15073412467312, 3.975915309639105, 5.552202674772324]
sum over smoothness: 22.828549270059295
smoothness_est:
[4.039041020820662, 4.826934863051663, 3.9856778907117967, 3.856298896521254, 5.273421657890175]
sum over smoothness_est: 21.98137432899555
SNR: [[26.88196181 28.11450426 26.36256401 26.81841431 26.62710032]]
objectiveValue: 22.828549270059295
objectiveValue_est: 21.98137432899555
error: 4.694088323409734e-15
############################################# iteration =  158  ########################################
Sensor
[0.05808373 0.0658778  0.11730886]
[0.05879622 0.070624   0.1142248 ]
[0.05758777 0.06548802 0.12653537]
[

2021-12-03 15:01:47,849:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.06432915 0.08445282 0.12449214]
[0.06084017 0.06251081 0.11750174]
[0.0565156  0.06806666 0.09082613]
[0.05618569 0.07048805 0.12573255]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17447
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.10e+00

  50   3.0316e+01   6.01e-09   5.89e-08   1.00e-01   1.26e+00s
plsh   3.0316e+01   7.52e-16   1.37e-14   --------   2.22e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    30.3161
run time:             2.22e+00s
optimal rho estimate: 1.47e-02

smoothness:
[1.657469064038223, 7.132282756383098, 7.279403684821126, 8.917684082845309, 6.727253748899104]
sum over smoothness: 31.714093336986863
smoothness_est:
[1.8423576321771855, 6.675391048527063, 6.916539835610058, 8.463532627302007, 6.418322316320761]
sum over smoothness_est: 30.316143459937074
SNR: [[24.4049159  25.11689846 26.05514601 26.63075712 25.55790381]]
objectiveValue: 31.714093336986863
objectiveValue_est: 30.316143459937074
error: 5.25956715024701e-15
############################################# iteration =  165  ########################################
Sensor
[0.05596034 0.06341812 0.11213658]
[0.06309539 0.08016547 0.11586268]
[0.05469948 0.07710563 0.14868655]

Sensor
[0.05270915 0.06571173 0.11773723]
[0.04968086 0.07436651 0.12811485]
[0.02568211 0.05596649 0.09384522]
[0.05283288 0.06116976 0.07491521]
[0.05148941 0.07401029 0.11618473]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17483
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

  50   2.3174e+01   5.33e-09   5.75e-08   1.00e-01   1.28e+00s
plsh   2.3174e+01   4.32e-16   1.36e-14   --------   2.14e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    23.1744
run time:             2.14e+00s
optimal rho estimate: 1.21e-02

smoothness:
[3.833970779566333, 6.181055060161713, 3.554954803955135, 6.911478160687784, 3.5557854811080754]
sum over smoothness: 24.03724428547904
smoothness_est:
[3.7978131687966985, 5.879831677455336, 3.429422744144093, 6.644603283827504, 3.4226973580409235]
sum over smoothness_est: 23.174368232264555
SNR: [[27.21962291 27.53740384 25.68891428 28.65807994 25.90932615]]
objectiveValue: 24.03724428547904
objectiveValue_est: 23.174368232264555
error: 4.749476193215505e-15
############################################# iteration =  174  ########################################
Sensor
[0.04622244 0.0605812  0.09704917]
[0.05511679 0.05931421 0.1288801 ]
[0.04577397 0.06551166 0.11065822

Sensor
[0.04043316 0.04887119 0.10498383]
[0.05482617 0.06205987 0.13009401]
[0.04058439 0.06334386 0.10018737]
[0.05110989 0.05735144 0.09759858]
[0.05153404 0.06685804 0.11654394]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17626
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

  50   2.0313e+01   4.71e-09   4.47e-08   1.00e-01   1.36e+00s
plsh   2.0313e+01   4.95e-16   7.24e-15   --------   2.31e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    20.3125
run time:             2.31e+00s
optimal rho estimate: 1.26e-02

smoothness:
[2.9047746135408765, 8.155149535964293, 5.63968074586546, 1.5432433040262135, 2.964718158436675]
sum over smoothness: 21.207566357833517
smoothness_est:
[2.9153519194691686, 7.591290109603973, 5.297230371693376, 1.6348008843094053, 2.873846864375706]
sum over smoothness_est: 20.312520149451633
SNR: [[26.70983603 26.18066026 25.68664234 26.30984882 24.86296073]]
objectiveValue: 21.207566357833517
objectiveValue_est: 20.312520149451633
error: 4.479349190315045e-15
############################################# iteration =  183  ########################################
Sensor
[0.0565322  0.07433422 0.10949228]
[0.05666216 0.06728275 0.10998471]
[0.05600442 0.07731046 0.119173

Sensor
[0.05055421 0.05993683 0.09414401]
[0.04468453 0.05279906 0.08894155]
[0.05667859 0.06955126 0.10732075]
[0.03143154 0.06175488 0.09759914]
[0.04354175 0.06919282 0.1251843 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17595
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

  50   2.2821e+01   4.93e-09   4.80e-08   1.00e-01   1.31e+00s
plsh   2.2821e+01   5.78e-16   1.03e-14   --------   2.35e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    22.8210
run time:             2.35e+00s
optimal rho estimate: 1.15e-02

smoothness:
[5.517744468166949, 5.4160634269883445, 4.140677159011564, 3.7613326465838073, 4.776710418226406]
sum over smoothness: 23.612528118977067
smoothness_est:
[5.29343665582242, 5.139015753350727, 4.107084336609616, 3.623923359435118, 4.657491518464588]
sum over smoothness_est: 22.820951623682472
SNR: [[28.31183297 26.7920683  30.11333319 26.74427237 28.61711488]]
objectiveValue: 23.612528118977067
objectiveValue_est: 22.820951623682472
error: 4.737919490331386e-15
############################################# iteration =  192  ########################################


2021-12-03 15:04:52,173:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.03671767 0.06486174 0.11748764]
[0.03695601 0.04936389 0.10801765]
[0.04531861 0.0679215  0.11672538]
[0.05416824 0.06582305 0.12428376]
[0.03902722 0.05120976 0.08356014]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17693
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

2021-12-03 15:05:12,168:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.03339176 0.0551225  0.0830865 ]
[0.05425725 0.07438369 0.10881669]
[0.03226623 0.06377213 0.08378716]
[0.06222808 0.07029518 0.11032811]
[0.0461533  0.05665824 0.10473035]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 2250, constraints m = 450
          nnz(P) + nnz(A) = 17501
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rh

  50   2.6870e+01   5.34e-09   4.99e-08   1.00e-01   1.13e+00s
plsh   2.6870e+01   4.54e-16   8.23e-15   --------   1.90e+00s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    26.8699
run time:             1.90e+00s
optimal rho estimate: 1.26e-02

smoothness:
[7.252699241071836, 5.498348244165183, 4.216689462026553, 6.115526532060938, 4.889309388745554]
sum over smoothness: 27.972572868070067
smoothness_est:
[6.867817240613819, 5.280815535112434, 4.219662933897463, 5.794377924856437, 4.707234036094483]
sum over smoothness_est: 26.869907670574637
SNR: [[26.51533988 26.48755913 28.74449589 26.25565033 25.7673442 ]]
objectiveValue: 27.972572868070067
objectiveValue_est: 26.869907670574637
error: 5.0435040047601075e-15
############################################# iteration =  199  ########################################
Sensor
[0.04086707 0.06457487 0.09101912]
[0.05049677 0.06885452 0.1053207 ]
[0.06024644 0.06977    0.11210404