In [1]:
import numpy as np
import matplotlib.pyplot as plt
from pygsp import graphs, filters, plotting
import pygsp as pg
from numpy.random import default_rng
from numpy.random import randint
from random import sample
import random
import cvxpy as cp

plotting.BACKEND = 'matplotlib'
plt.rcParams['figure.figsize'] = (10, 5)

In [2]:
def createGraph(Nodes,i,graphType):
    while True:
        s = np.array(sample(range(1, 10000), 1))
        G = pg.graphs.Sensor(N=Nodes, seed = s)
        typeName = 'Sensor'
            
        if (G.is_connected() and not(G.is_directed())):
            break
    if i==0:        
        print(typeName)
           
    G.compute_fourier_basis()
    W = np.random.uniform(size=(2,1))
    x =  G.U[:,1:3]@W
    x = x/np.max(np.abs(x))
    eigenvalue = G.e
    print(eigenvalue[1:4])

    return G,x

In [3]:
def computeMainSignal(signals,k,N):
    x = np.zeros((N,1))
    for i in range(k):
        x = x + signals[:,i].reshape(N,1)
    return x

In [4]:
def computeSmoothness(signals,graphs,k):
    smoothness = []
    sumOverSmoothness = 0
    for i in range(k):
        smoothness.append(signals[:,i].T@graphs[i].L@signals[:,i])
        sumOverSmoothness = sumOverSmoothness + smoothness[i]
    return sumOverSmoothness,smoothness

In [5]:
def decomposeGraphSignal(mainSignal,signals,graphs,k,N):
    A = np.tile(np.identity(N), (1, k))
    
    H = np.zeros((N*k,N*k))
    for i in range(k):
        g = graphs[i].L
        H[i*N:(i+1)*N,i*N:(i+1)*N] = g.toarray()
        
        
    X = cp.Variable((N*k,1))
    objective = cp.Minimize(cp.quad_form(X, H)) 
    
    constraints = [ A @ X == mainSignal]
    prob = cp.Problem(objective, constraints)
    prob.solve(verbose=True)
    
    temp = X.value
    X_hat = temp.reshape(N,k, order='F')
    
    return X_hat

In [6]:
def makeMeanZero(signals,k):
    for i in range(k):
            signals[:,i] = signals[:,i] - np.mean(signals[:,i])
            
    return signals

In [7]:
def calculateSNR(est_signals,signals,k):
    SNR = np.zeros((1,k))
    for i in range(k):
        SNR[0,i]=(10*np.log10(np.linalg.norm(signals[:,i])**2/np.linalg.norm(signals[:,i]-est_signals[:,i])**2))
    return SNR

In [8]:
N = 250  # number of nodes
k = 5    # number of graphs
np.random.seed(0)
random.seed(0)
iteration = 200
av_snr = np.zeros((1,k))

for itera in range(1,iteration+1):
    print('############################################# iteration = ',itera,' ########################################')
    # create graph and graph signals
    graphType = randint(1, 3, 1)
    graph_list = []
    signals = np.zeros((N,k))
    for i in range(k):
        G , x = createGraph(N,i,graphType)
        graph_list.append(G)
        signals[:,[i]] = x

    # calculate the main signal : x = x1+x2+...+x4
    mainSignal = computeMainSignal(signals,k,N)
    mainSignal = mainSignal - np.mean(mainSignal)

    # decompose graph signal
    estimated_signals = decomposeGraphSignal(mainSignal,signals,graph_list,k,N)

    # calculate graph signals' smoothness
    sumOverSmoothness,smoothness = computeSmoothness(signals,graph_list,k)
    print('smoothness:')
    print(smoothness)
    print('sum over smoothness:',sumOverSmoothness)

    # calculate estimated graph signals' smoothness
    sumOverSmoothness_est,smoothness_est = computeSmoothness(estimated_signals,graph_list,k)
    print('smoothness_est:')
    print(smoothness_est)
    print('sum over smoothness_est:',sumOverSmoothness_est)

    # make mean of the estimated signals zero to remove DC values
    estimated_signals = makeMeanZero(estimated_signals,k)

    # calculate SNRs
    SNRs = calculateSNR(estimated_signals,signals,k)
    print('SNR:',SNRs)
    av_snr = av_snr + SNRs/iteration

    # compute objective values
    objectiveValue = sumOverSmoothness
    objectiveValue_est = sumOverSmoothness_est
    print('objectiveValue:',objectiveValue)
    print('objectiveValue_est:',objectiveValue_est)

    # compute error
    error = np.linalg.norm(mainSignal-estimated_signals@np.ones((k,1)))
    print('error:',error)
    
    
print('av_snr: ',av_snr)
print('total_av_snr: ',np.mean(av_snr))

############################################# iteration =  1  ########################################
Sensor
[0.09819918 0.13965542 0.16814379]
[0.08541946 0.10730097 0.19473386]
[0.07636719 0.12163677 0.18823118]
[0.08208824 0.10205125 0.14759177]
[0.08055813 0.1055017  0.15590231]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9531
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: o

2021-12-03 14:50:20,252:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.06557593 0.09028861 0.15870866]
[0.08639341 0.12378437 0.19321071]
[0.1037146  0.10600691 0.19469326]
[0.11782776 0.12662681 0.19316097]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9406
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.28e+00 

smoothness:
[3.2744446453234826, 3.7095383494076053, 4.680737937420424, 4.880300272850462, 9.483946186746087]
sum over smoothness: 26.02896739174806
smoothness_est:
[3.210031712618238, 3.7163880303752626, 4.40829238574913, 4.33067736575394, 8.941727325568817]
sum over smoothness_est: 24.607116820065386
SNR: [[23.16960777 24.5870511  23.05565318 20.7673194  26.41223936]]
objectiveValue: 26.02896739174806
objectiveValue_est: 24.607116820065386
error: 3.83540809174956e-15
############################################# iteration =  8  ########################################
Sensor
[0.09752216 0.14432902 0.24682651]
[0.09135297 0.12429003 0.18001639]
[0.07929894 0.11707833 0.19021406]
[0.06660332 0.11367299 0.15993293]
[0.06619359 0.11432317 0.18293618]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
--------

2021-12-03 14:50:35,281:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.11429042 0.12359591 0.21248653]
[0.12682189 0.15123041 0.28132889]
[0.07230502 0.08254295 0.16755024]
[0.08970032 0.11045674 0.22233109]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9726
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.20e+00 

smoothness:
[11.86199709421228, 5.674693616021649, 4.811411401723093, 7.602558328059079, 5.265676147259463]
sum over smoothness: 35.21633658727556
smoothness_est:
[10.742806762085541, 5.228353320258975, 4.65961444244845, 6.793935185405817, 4.9613973787223316]
sum over smoothness_est: 32.386107088921115
SNR: [[22.35257033 19.31451195 19.89082292 19.84032214 19.51322043]]
objectiveValue: 35.21633658727556
objectiveValue_est: 32.386107088921115
error: 3.977577659950535e-15
############################################# iteration =  16  ########################################
Sensor
[0.06046173 0.089525   0.11743502]
[0.11509497 0.12485859 0.19366226]
[0.0745012  0.12278828 0.25229231]
[0.0943599  0.13625921 0.24178295]
[0.09573356 0.12294983 0.23825849]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
------

[0.09861496 0.11584785 0.22450726]
[0.11108972 0.13450943 0.31893092]
[0.09089346 0.10568646 0.1803686 ]
[0.08514097 0.13034705 0.19397633]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9547
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.36e+00 

smoothness:
[1.689254405224966, 5.551275974497943, 5.0030623870629185, 2.7722770626207067, 4.355012913001811]
sum over smoothness: 19.370882742408345
smoothness_est:
[1.713948727688777, 5.20995404256204, 4.523846634946778, 2.4896886326151186, 3.957994432914962]
sum over smoothness_est: 17.895432470727677
SNR: [[19.00410964 23.72578165 20.78116817 18.19220322 20.86296224]]
objectiveValue: 19.370882742408345
objectiveValue_est: 17.895432470727677
error: 2.8631805947323253e-15
############################################# iteration =  25  ########################################
Sensor
[0.08000008 0.10113756 0.1765212 ]
[0.06520508 0.09328254 0.12324379]
[0.0852318  0.14339799 0.23385689]
[0.08585247 0.10744261 0.16888836]
[0.0902515  0.10786972 0.15721836]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
--

2021-12-03 14:51:03,360:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.09036769 0.11648355 0.18321346]
[0.11794396 0.11999835 0.23869528]
[0.12934309 0.14259867 0.20139438]
[0.07781782 0.10904335 0.18772089]
[0.07915476 0.10522855 0.21138958]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9697
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

2021-12-03 14:51:09,568:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.1073105  0.13196265 0.18125685]
[0.09323942 0.11622968 0.18847198]
[0.09729009 0.13784255 0.22748801]
[0.07107601 0.08147603 0.19454864]
[0.08479328 0.14535817 0.19799567]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9377
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

smoothness_est:
[1.1510466498009764, 4.389903913730312, 6.683392791368306, 5.686848151552463, 4.213189829619517]
sum over smoothness_est: 22.124381336071576
SNR: [[18.56536766 19.40899615 24.29871325 21.4654745  22.03278524]]
objectiveValue: 23.779323830492956
objectiveValue_est: 22.124381336071576
error: 3.535666475482887e-15
############################################# iteration =  36  ########################################
Sensor
[0.10044281 0.13723308 0.1498742 ]
[0.09641402 0.10706105 0.16791336]
[0.09098196 0.11214914 0.23196315]
[0.09096224 0.13509848 0.23795667]
[0.07601319 0.09442244 0.18369413]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9474
set

[0.0775608  0.10630048 0.21268182]
[0.11724807 0.12584997 0.24629539]
[0.09986421 0.11954187 0.17071613]
[0.10388005 0.13385963 0.17939304]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9559
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.44e+00 

smoothness:
[5.7929358372293445, 6.823933171538618, 2.324822121363738, 3.808770685113365, 3.8957260023493174]
sum over smoothness: 22.646187817594384
smoothness_est:
[5.39877993697333, 6.118802805553375, 2.503076259371696, 3.4712758893172944, 3.584569879680984]
sum over smoothness_est: 21.07650477089668
SNR: [[23.23868003 22.03916749 22.96412099 20.24614273 19.97934513]]
objectiveValue: 22.646187817594384
objectiveValue_est: 21.07650477089668
error: 3.875856854374136e-15
############################################# iteration =  45  ########################################
Sensor
[0.0964751  0.12730723 0.15047717]
[0.08289708 0.13320134 0.17492748]
[0.09318807 0.10180722 0.17173788]
[0.09558529 0.12499833 0.19374336]
[0.06486362 0.08706077 0.15772301]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----

[0.09148316 0.10469475 0.18631384]
[0.09171607 0.10582065 0.15215711]
[0.06983881 0.12411783 0.19519651]
[0.06905191 0.10746032 0.14326182]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9571
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   1.96e+00 

plsh   3.0613e+01   5.29e-16   1.20e-14   --------   4.13e-01s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    30.6130
run time:             4.13e-01s
optimal rho estimate: 1.83e-02

smoothness:
[2.7338172478846063, 5.920272842040684, 10.349327542211313, 5.152687594521202, 8.483540623151697]
sum over smoothness: 32.639645849809504
smoothness_est:
[2.7540906026324663, 5.451488488018957, 9.715292655263447, 5.040641753071204, 7.651519305613777]
sum over smoothness_est: 30.61303280459985
SNR: [[19.46541389 21.34494379 24.67096343 23.89730203 22.00317708]]
objectiveValue: 32.639645849809504
objectiveValue_est: 30.61303280459985
error: 3.677898923643691e-15
############################################# iteration =  54  ########################################
Sensor
[0.10862836 0.11381085 0.18460979]
[0.1069834  0.13031342 0.24992917]
[0.05078451 0.07605802 0.14191151]
[0.06694861 0.15773397 0.19516992]
[0.04369513 0.10489439 0.15

[0.1307468  0.14777468 0.22780711]
[0.06732406 0.10615282 0.2139606 ]
[0.10499647 0.13606645 0.22553046]
[0.09870565 0.14981862 0.22069564]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9521
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.26e+00 

Sensor
[0.11843515 0.12613956 0.19407236]
[0.09631726 0.1157568  0.22031845]
[0.06436388 0.08381305 0.16840651]
[0.08911797 0.10972204 0.20404535]
[0.10885715 0.12416206 0.18038031]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9400
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

[0.07057213 0.0910376  0.14129379]
[0.0779973  0.10835014 0.18764924]
[0.07624051 0.12177424 0.19081915]
[0.06344053 0.08949305 0.16026302]
[0.07332666 0.09942546 0.16506604]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9406
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho       

[0.06088126 0.10194635 0.13148215]
[0.10582762 0.13005576 0.19469661]
[0.08569988 0.10826131 0.19972897]
[0.10045956 0.15422823 0.23727481]
[0.08948893 0.13237068 0.1908612 ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9544
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho       

smoothness_est:
[6.388980924463446, 7.572745542819263, 5.190726742462093, 3.316987884887116, 5.390274498741888]
sum over smoothness_est: 27.859715593373807
SNR: [[26.28593177 22.48138623 22.94165683 23.53283968 22.91969458]]
objectiveValue: 29.49647223758639
objectiveValue_est: 27.859715593373807
error: 4.1882154741914105e-15
############################################# iteration =  78  ########################################
Sensor
[0.10777913 0.15344193 0.21095217]
[0.0800867  0.11798729 0.17281374]
[0.04192867 0.0899858  0.14879611]
[0.1000922  0.10730081 0.1731587 ]
[0.09824712 0.10664722 0.17339572]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9648
sett

[0.10679573 0.14619282 0.20157238]
[0.05564043 0.11253855 0.18109111]
[0.10574176 0.11690349 0.19293241]
[0.07560806 0.09184552 0.17380676]


2021-12-03 14:52:17,352:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.0823875  0.11126776 0.17504287]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9553
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.69e+00   4.21e+03   1.00e-01   9.73e-02s
  50   3.0861e+01   6.45e-09   5.67e-08   1.00e-01   1.56e-01s
plsh   3

2021-12-03 14:52:23,458:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.08135345 0.12459877 0.23023471]
[0.06582119 0.08149572 0.15737646]
[0.07335815 0.13154872 0.20291159]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9435
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.29e+00   4.28e+03   1.00e-01   9.17e-02s
 

plsh   1.6627e+01   5.26e-16   8.96e-15   --------   2.90e-01s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    16.6273
run time:             2.90e-01s
optimal rho estimate: 1.70e-02

smoothness:
[4.806642430473451, 3.099768781678816, 4.050066816492203, 5.182961439500296, 0.47756006127837825]
sum over smoothness: 17.616999529423143
smoothness_est:
[4.466847845897102, 2.960030804070661, 3.7696485852774786, 4.792921960285031, 0.63786849547882]
sum over smoothness_est: 16.627317691009093
SNR: [[24.49441455 23.63974397 23.29821827 23.54983834 18.18263846]]
objectiveValue: 17.616999529423143
objectiveValue_est: 16.627317691009093
error: 3.280123571389473e-15
############################################# iteration =  90  ########################################
Sensor
[0.08203494 0.1033375  0.20906703]
[0.08744397 0.11373259 0.20440042]
[0.06730091 0.09695186 0.15013365]
[0.0842517  0.09708787 0.18312284]
[0.10098154 0.10748028 0.1

2021-12-03 14:52:32,863:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.04812017 0.08170898 0.16836697]
[0.08860702 0.11753272 0.16153396]
[0.08641812 0.11138346 0.223407  ]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9431
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.58e+00   2.60e+03   1.00e-01   8.37e-02s
 

2021-12-03 14:52:39,792:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.09780955 0.12311452 0.16674132]
[0.12082558 0.12445919 0.21164449]
[0.08717051 0.1178995  0.15599878]
[0.10619889 0.14339241 0.22810423]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9445
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.39e+00 

Sensor
[0.08438479 0.10621059 0.15007443]
[0.09384354 0.10422216 0.20111134]
[0.09322285 0.10531718 0.17563695]
[0.13385714 0.14253479 0.25161787]
[0.05657834 0.09973724 0.17409409]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9555
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

Sensor
[0.09156011 0.14650461 0.23845669]
[0.09051624 0.12952094 0.16749232]
[0.05793932 0.08426178 0.16460583]
[0.09148474 0.13017064 0.20486742]
[0.08798655 0.09465354 0.17155841]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9519
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

2021-12-03 14:52:55,884:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.09880204 0.13654539 0.17794136]
[0.05749938 0.07410052 0.21132226]


2021-12-03 14:52:58,567:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.07599279 0.10324781 0.18821376]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9595
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.18e+00   4.17e+03   1.00e-01   8.50e-02s
  50   2.2406e+01   5.58e-09   5.62e-08   1.00e-01   1.35e-01s
plsh   2

[0.04812017 0.08170898 0.16836697]
[0.08056144 0.11979144 0.2375453 ]
[0.05346879 0.0898005  0.20915005]
[0.10186557 0.13022047 0.18324392]
[0.10549335 0.10926611 0.20781915]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9399
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho       

plsh   1.9270e+01   3.80e-16   9.59e-15   --------   3.12e-01s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    19.2702
run time:             3.12e-01s
optimal rho estimate: 1.76e-02

smoothness:
[1.0967319993267348, 2.2123392159814252, 5.847264457357715, 3.1674820928318845, 8.070826245875631]
sum over smoothness: 20.39464401137339
smoothness_est:
[1.2767931118343676, 2.164102568437189, 5.53035573927652, 3.0657866241675347, 7.233159496250609]
sum over smoothness_est: 19.27019753996622
SNR: [[22.70014187 20.95180792 25.59106588 23.00773819 23.34808737]]
objectiveValue: 20.39464401137339
objectiveValue_est: 19.27019753996622
error: 3.368214906655546e-15
############################################# iteration =  116  ########################################
Sensor
[0.1085228  0.14205317 0.25096198]
[0.10346293 0.10976938 0.20946879]
[0.08133085 0.09310945 0.16051664]
[0.07112006 0.11808744 0.19234183]
[0.0808329  0.11781415 0.19

Sensor
[0.07312664 0.10023565 0.16492107]


2021-12-03 14:53:17,607:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.07473794 0.08745916 0.14983777]
[0.09153629 0.10265117 0.16922246]
[0.09530738 0.1264702  0.22180976]
[0.0703781  0.12414637 0.18293318]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9455
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.26e+00 

Sensor
[0.07414768 0.12558163 0.18640679]
[0.06934857 0.09563749 0.21672013]
[0.08064291 0.1277411  0.24367027]
[0.08265086 0.114229   0.15145976]
[0.06822589 0.10259419 0.19981098]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9494
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

Sensor
[0.08295574 0.10138348 0.178836  ]
[0.05933147 0.09670901 0.21138252]
[0.05775786 0.10480654 0.17566699]
[0.08748825 0.11106714 0.17221304]
[0.08483663 0.09841175 0.15912674]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9522
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

Sensor
[0.1133402  0.13608647 0.18625118]
[0.07433845 0.09544073 0.19509268]
[0.10036787 0.10298962 0.20793263]
[0.08609652 0.1100863  0.20699176]
[0.09223498 0.11385489 0.19259688]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9409
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

[0.06275432 0.1083064  0.15492868]
[0.03905484 0.13319328 0.18529323]
[0.06677573 0.09091115 0.15349171]
[0.06678452 0.08830949 0.17575648]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9615
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.26e+00 

Sensor
[0.10471111 0.12601853 0.18598219]
[0.12536635 0.14513997 0.20939102]
[0.07718361 0.10690512 0.24328451]
[0.10324194 0.16851655 0.26340329]
[0.08881078 0.13151082 0.21767613]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9595
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

2021-12-03 14:53:49,727:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.07834512 0.10354451 0.15341023]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9569
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.54e+00   3.17e+03   1.00e-01   8.97e-02s
  50   1.8604e+01   4.45e-09   4.28e-08   1.00e-01   1.43e-01s
plsh   1

Sensor
[0.11906599 0.15078323 0.27446062]
[0.09373962 0.12478036 0.19355803]
[0.06766429 0.09682359 0.14129331]
[0.05364956 0.11479007 0.1322783 ]
[0.10132481 0.13342692 0.21404694]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9424
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

Sensor
[0.07261127 0.14152144 0.17762995]
[0.10749999 0.12626761 0.22341972]
[0.06494381 0.10089242 0.21153156]
[0.07216097 0.07930613 0.16388562]
[0.08252925 0.10815616 0.14633991]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9480
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

[0.09064926 0.1222619  0.22456285]
[0.08190574 0.11051333 0.18113614]
[0.09794934 0.10722521 0.21801346]
[0.0935668  0.12441395 0.22431847]
[0.06112984 0.10034559 0.21726905]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9588
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho       

Sensor
[0.0947121  0.13545174 0.23629382]
[0.09873898 0.12754449 0.21515781]
[0.07410459 0.10445321 0.14560906]
[0.07581815 0.10499413 0.15352333]
[0.11058853 0.12604477 0.21370821]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9633
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

2021-12-03 14:54:18,573:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.
2021-12-03 14:54:21,298:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.11766946 0.12897029 0.23158871]
[0.05168779 0.09567031 0.17286875]
[0.09665468 0.1305886  0.24908016]
[0.08716917 0.12656204 0.20193011]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9670
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.27e+00 

2021-12-03 14:54:29,066:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.07016819 0.10606092 0.16571562]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9479
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.98e+00   3.54e+03   1.00e-01   1.01e-01s
  50   2.6234e+01   5.23e-09   4.77e-08   1.00e-01   1.59e-01s
plsh   2

2021-12-03 14:54:37,183:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


Sensor
[0.07318361 0.0983697  0.19406754]
[0.07502804 0.12690253 0.21295352]
[0.10140017 0.14558409 0.25493526]
[0.10161854 0.11484654 0.22420898]
[0.07262074 0.10744478 0.17964523]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9485
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

2021-12-03 14:54:42,739:[WARNING](pygsp.graphs.sensor.__init__): Graph is not connected.


[0.084995   0.11993401 0.19403871]
[0.07765116 0.10908675 0.17884088]
[0.08288292 0.08975832 0.20593643]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9291
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   2.94e+00   3.67e+03   1.00e-01   1.41e-01s
 

Sensor
[0.07557608 0.11580752 0.13124151]
[0.0874899  0.10102821 0.18044912]
[0.09587157 0.1167639  0.22185945]
[0.07811925 0.09202005 0.17551776]
[0.08474475 0.11724491 0.20495273]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9548
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho

[0.07040376 0.09618938 0.15234906]
[0.11209245 0.12357051 0.1811622 ]
[0.05279168 0.10793208 0.19347778]
[0.10275116 0.12249664 0.20618437]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9471
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.35e+00 

[0.10285858 0.12014942 0.21104985]
[0.07749661 0.11737327 0.16107392]
[0.07239517 0.1156114  0.19581658]
[0.08536874 0.116432   0.20873613]
[0.07525091 0.11709378 0.21778554]
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 1250, constraints m = 250
          nnz(P) + nnz(A) = 9470
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on, time_limit: off

iter   objective    pri res    dua res    rho       